#!/usr/bin/env python3
"""Generate the image-validation fixture corpus and embed it as
test/wasi/MediaFixtures.mo (Motoko has no filesystem access under wasi tests).

Every fixture is a REAL file written by Pillow (or a deliberate byte-level
corruption of one), kept small; cap-boundary bodies are built at test time
in Motoko by padding after EOI/IEND (header-bounded validation permits
trailing bytes — documented in Media.mo). A manifest maps each fixture to
(declared content-type, class, expected verdict) consumed by Media.test.mo.
"""
import io
import os
import struct

from PIL import Image

HERE = os.path.dirname(__file__)
FIXDIR = os.path.join(HERE, "image-fixtures")
os.makedirs(FIXDIR, exist_ok=True)

fixtures = {}  # name -> bytes


def noise(w, h, alpha=False):
    mode = "RGBA" if alpha else "RGB"
    img = Image.new(mode, (w, h))
    px = img.load()
    for y in range(h):
        for x in range(w):
            v = ((x * 37) ^ (y * 101)) & 0xFF
            px[x, y] = (v, (v * 7) & 0xFF, (v * 13) & 0xFF, 128) if alpha \
                else (v, (v * 7) & 0xFF, (v * 13) & 0xFF)
    return img


def enc(img, fmt, **kw):
    buf = io.BytesIO()
    img.save(buf, fmt, **kw)
    return buf.getvalue()


# ── valid, in-bounds (dims ≤256 → pass avatar+logo+photo) ──
fixtures["jpeg_ok_64"] = enc(noise(64, 64), "JPEG", quality=80)
fixtures["jpeg_progressive_96"] = enc(noise(96, 48), "JPEG", quality=70, progressive=True)  # SOF2
fixtures["png_ok_64"] = enc(noise(64, 64), "PNG")
fixtures["gif_ok_64"] = enc(noise(64, 64).convert("P"), "GIF")
fixtures["webp_lossy_64"] = enc(noise(64, 64), "WEBP", quality=75)              # VP8
fixtures["webp_lossless_64"] = enc(noise(64, 64), "WEBP", lossless=True)        # VP8L
fixtures["webp_vp8x_64"] = enc(noise(64, 64, alpha=True), "WEBP", quality=75)   # alpha → VP8X

# ── dimension boundaries ──
fixtures["jpeg_256"] = enc(noise(256, 256), "JPEG", quality=60)     # == avatar/logo dim cap
fixtures["jpeg_257w"] = enc(noise(257, 32), "JPEG", quality=60)     # avatar dim + 1 (width)
fixtures["png_257h"] = enc(noise(32, 257), "PNG")                   # avatar dim + 1 (height)
fixtures["gif_300w"] = enc(noise(300, 8).convert("P"), "GIF")
fixtures["webp_257w"] = enc(noise(257, 8), "WEBP", quality=75)
fixtures["webp_l_257h"] = enc(noise(8, 257), "WEBP", lossless=True)
fixtures["jpeg_1600w"] = enc(noise(1600, 8), "JPEG", quality=50)    # == photo dim cap
fixtures["jpeg_1601w"] = enc(noise(1601, 8), "JPEG", quality=50)    # photo dim + 1

# ── malformed ──
fixtures["trunc_png_20"] = fixtures["png_ok_64"][:20]        # cut inside IHDR
fixtures["trunc_jpeg_soi"] = b"\xff\xd8"                     # SOI only
fixtures["jpeg_no_sof"] = b"\xff\xd8\xff\xd9"                # SOI + EOI, no SOF
png_bad = bytearray(fixtures["png_ok_64"]); png_bad[12:16] = b"JUNK"
fixtures["png_bad_ihdr"] = bytes(png_bad)                    # first chunk not IHDR
webp_bad = bytearray(fixtures["webp_lossy_64"]); webp_bad[8:12] = b"WEBQ"
fixtures["webp_bad_fourcc"] = bytes(webp_bad)
gif_bad = bytearray(fixtures["gif_ok_64"]); gif_bad[0:6] = b"GIF88a"
fixtures["gif_bad_version"] = bytes(gif_bad)
fixtures["empty"] = b""
fixtures["garbage"] = bytes((i * 89 + 7) & 0xFF for i in range(4096))
# PNG with IHDR width=0 (CRC left stale — Media.mo parses headers, no CRC).
png_zero = bytearray(fixtures["png_ok_64"]); png_zero[16:20] = struct.pack(">I", 0)
fixtures["png_zero_width"] = bytes(png_zero)
# WebP VP8 with a corrupted start code (0x9d012a damaged).
wl = bytearray(fixtures["webp_lossy_64"])
sc = bytes(wl).find(b"\x9d\x01\x2a")
assert sc > 0, "VP8 start code not found"
wl[sc] = 0x00
fixtures["webp_bad_startcode"] = bytes(wl)

# Sanity: verify every VP8-variant fixture actually carries the fourcc we claim.
for name, four in (("webp_lossy_64", b"VP8 "), ("webp_lossless_64", b"VP8L"),
                   ("webp_vp8x_64", b"VP8X")):
    assert fixtures[name][12:16] == four, (name, fixtures[name][12:16])

# Manifest rows: (name, declared content type, dims)
DIMS = {
    "jpeg_ok_64": (64, 64), "jpeg_progressive_96": (96, 48), "png_ok_64": (64, 64),
    "gif_ok_64": (64, 64), "webp_lossy_64": (64, 64), "webp_lossless_64": (64, 64),
    "webp_vp8x_64": (64, 64), "jpeg_256": (256, 256), "jpeg_257w": (257, 32),
    "png_257h": (32, 257), "gif_300w": (300, 8), "webp_257w": (257, 8),
    "webp_l_257h": (8, 257), "jpeg_1600w": (1600, 8), "jpeg_1601w": (1601, 8),
}

for name, data in fixtures.items():
    with open(os.path.join(FIXDIR, name + ".bin"), "wb") as f:
        f.write(data)

# ── Emit MediaFixtures.mo ──
def mo_blob(data: bytes) -> str:
    return '"' + "".join(f"\\{b:02x}" for b in data) + '" : Blob'

lines = [
    "// GENERATED by test/gen-image-fixtures.py — DO NOT EDIT BY HAND.",
    "// Real image fixtures for the Media.mo image-validation suite.",
    "module {",
]
for name, data in fixtures.items():
    lines.append(f"  public let {name} : Blob = {mo_blob(data)};")
for name, (w, hgt) in DIMS.items():
    lines.append(f"  public let {name}_dims : (Nat, Nat) = ({w}, {hgt});")
lines.append("}")
with open(os.path.join(HERE, "wasi/MediaFixtures.mo"), "w") as f:
    f.write("\n".join(lines) + "\n")

total = sum(len(v) for v in fixtures.values())
print(f"{len(fixtures)} fixtures, {total} bytes total")
for n, v in sorted(fixtures.items()):
    print(f"  {n:22s} {len(v):6d} B")
