#!/usr/bin/env bash
# run-tree-reference.sh — the certified-tree reference check: the certified-tree byte-for-byte reference check gate.
#
#   PASS bound (committed before running): the Motoko runner's output over
#   ALL fixture scripts is BYTE-IDENTICAL (diff -u == empty) to the Rust
#   reference binary's output, AND the 00-pinned root equals the literal
#   pinned in asset_tree.rs:360.
#
#   --teeth: prove the harness can fail — corrupt one path label on the
#   Motoko side only; the diff MUST go RED, then the corruption is undone.
#
# Exit 0 = gate green. Any other exit = gate red.
set -euo pipefail
cd "$(dirname "$0")/.."

MOC=~/.cache/mops/moc/1.4.1/moc
WASMTIME=~/.cache/mops/wasmtime/45.0.2/wasmtime
REF=test/tree-reference
PINNED_ROOT="02e55a8285b11008aa8caa0459c05322ef717771eb88101c0bdd9928d69a90f6"
# md5 of the upstream reference `asset_tree.rs` (the Egypt-L1 media
# canister) as of the 2026-07-30 port. Re-syncing the reference means
# updating this constant IN THE SAME COMMIT as the copy.
REF_MD5="0f8473506ce0e2cb0667aafb9f18a032"
OUT=$(mktemp -d)
trap 'rm -rf "$OUT"' EXIT

# 0. The Rust binary here must wrap a byte-identical copy of the upstream
#    `asset_tree.rs`. Always check the pinned md5; when a maintainer has the
#    upstream checkout to hand, point UPSTREAM_ASSET_TREE at it for a direct
#    byte comparison as well.
if [[ -n "${UPSTREAM_ASSET_TREE:-}" ]]; then
  if ! cmp -s "$UPSTREAM_ASSET_TREE" $REF/src/asset_tree.rs; then
    echo "RED: asset_tree.rs has drifted from $UPSTREAM_ASSET_TREE" >&2
    exit 1
  fi
fi
GOT_MD5=$(md5sum "$REF/src/asset_tree.rs" | cut -d' ' -f1)
if [[ "$GOT_MD5" != "$REF_MD5" ]]; then
  echo "RED: tree-reference asset_tree.rs md5 $GOT_MD5 != pinned upstream $REF_MD5" >&2
  exit 1
fi

# 1. Build the Rust reference binary and regenerate expected outputs from the scripts.
(cd $REF && cargo build --release -q)
: > "$OUT/expected-all.txt"
for f in test/tree-fixtures/*.txt; do
  name=$(basename "$f" .txt)
  echo "### $name" >> "$OUT/expected-all.txt"
  $REF/target/release/tree-reference < "$f" >> "$OUT/expected-all.txt"
done

# 2. Anchor: the pinned vector from asset_tree.rs:360 (independent literal).
if ! grep -A1 '^### 00-pinned$' "$OUT/expected-all.txt" | grep -q "root=$PINNED_ROOT"; then
  echo "RED: Rust reference binary no longer reproduces the pinned root $PINNED_ROOT" >&2
  exit 1
fi

# 3. Embed the scripts for the Motoko runner (no filesystem under wasi test).
python3 - << 'EOF'
import os
fixdir = "test/tree-fixtures"
entries = []
for f in sorted(os.listdir(fixdir)):
    if not f.endswith(".txt"):
        continue
    name = f[:-4]
    body = open(os.path.join(fixdir, f)).read()
    esc = body.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
    entries.append(f'    ("{name}", "{esc}"),')
src = (
    "// GENERATED by test/run-tree-reference.sh from test/tree-fixtures/*.txt — DO NOT EDIT.\n"
    "module {\n  public let all : [(Text, Text)] = [\n"
    + "\n".join(entries) + "\n  ];\n}\n"
)
open("test/wasi/TreeReferenceScripts.mo", "w").write(src)
EOF

# Optional teeth corruption: one path label, Motoko side only.
if [[ "${1:-}" == "--teeth" ]]; then
  sed -i 's|/avatar/aaaaa-aa |/avatar/aaaaa-CORRUPT |' test/wasi/TreeReferenceScripts.mo
fi

# 4. Compile + run the Motoko runner.
$MOC -wasi-system-api --package core .mops/core@2.5.0/src \
  -o "$OUT/tree-reference.wasm" test/wasi/TreeReference.mo 2> "$OUT/moc-warnings.txt" || {
  cat "$OUT/moc-warnings.txt" >&2; exit 1; }
$WASMTIME run "$OUT/tree-reference.wasm" > "$OUT/mo-all.txt"

# 5. The gate: byte-identical.
if diff -u "$OUT/expected-all.txt" "$OUT/mo-all.txt" > "$OUT/diff.txt"; then
  if [[ "${1:-}" == "--teeth" ]]; then
    # Regenerate the clean embedding before reporting.
    "$0" > /dev/null 2>&1 || true
    echo "TEETH FAILURE: corrupted label still diffed clean — harness has no teeth" >&2
    exit 1
  fi
  lines=$(wc -l < "$OUT/expected-all.txt")
  echo "TREE REFERENCE GREEN: $lines lines byte-identical across $(ls test/tree-fixtures/*.txt | wc -l) fixture scripts"
else
  if [[ "${1:-}" == "--teeth" ]]; then
    echo "TEETH OK (RED as expected on corrupted label):"
    head -6 "$OUT/diff.txt"
    # Restore the clean embedding.
    "$0" > /dev/null
    exit 0
  fi
  echo "TREE REFERENCE RED:" >&2
  head -30 "$OUT/diff.txt" >&2
  exit 1
fi
